//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cCategoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cCategoria()
        {
            this.cMenu = new HashSet<cMenu>();
        }
    
        public int idcCategoria { get; set; }
        public int idcSucursal { get; set; }
        public string nombreCateria { get; set; }
    
        public virtual cSucursal cSucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cMenu> cMenu { get; set; }
    }
}
