//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cDocumento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cDocumento()
        {
            this.eEmpleadoDocumentacion = new HashSet<eEmpleadoDocumentacion>();
        }
    
        public int idcDocumento { get; set; }
        public string claveDocumento { get; set; }
        public string documento { get; set; }
        public Nullable<bool> obligatorio { get; set; }
        public string responsable { get; set; }
        public string estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eEmpleadoDocumentacion> eEmpleadoDocumentacion { get; set; }
    }
}
