//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cInventario
    {
        public int idcIngrediente { get; set; }
        public int idcSucursal { get; set; }
        public string nombreIngrediente { get; set; }
        public decimal cantidadActual { get; set; }
        public string unidadMedida { get; set; }
        public decimal stockMinimo { get; set; }
    
        public virtual cSucursal cSucursal { get; set; }
    }
}
