//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cMenu()
        {
            this.dPedido = new HashSet<dPedido>();
        }
    
        public int idcMenu { get; set; }
        public int idcCategoria { get; set; }
        public string nombre_platillo { get; set; }
        public string descripcion { get; set; }
        public decimal precio { get; set; }
        public Nullable<bool> disponible { get; set; }
    
        public virtual cCategoria cCategoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dPedido> dPedido { get; set; }
    }
}
