//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cMunicipio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cMunicipio()
        {
            this.dEmpleadoDomicilio = new HashSet<dEmpleadoDomicilio>();
        }
    
        public int idcMunicipio { get; set; }
        public int idcEntidadFederativa { get; set; }
        public string clave { get; set; }
        public string municipio { get; set; }
    
        public virtual cEntidadFederativa cEntidadFederativa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dEmpleadoDomicilio> dEmpleadoDomicilio { get; set; }
    }
}
