//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cSucursal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cSucursal()
        {
            this.cCategoria = new HashSet<cCategoria>();
            this.cInventario = new HashSet<cInventario>();
            this.cMesa = new HashSet<cMesa>();
            this.mPlaza = new HashSet<mPlaza>();
        }
    
        public int idcSucursal { get; set; }
        public int idcEmpresa { get; set; }
        public string sucursal { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public decimal latitud { get; set; }
        public decimal longitud { get; set; }
        public string estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cCategoria> cCategoria { get; set; }
        public virtual cEmpresa cEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cInventario> cInventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cMesa> cMesa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mPlaza> mPlaza { get; set; }
    }
}
