//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cUsuario
    {
        public int idcUsuario { get; set; }
        public int idcEmpresa { get; set; }
        public int idmEmpleado { get; set; }
        public string usuario { get; set; }
        public string clave { get; set; }
        public string estatus { get; set; }
    
        public virtual cEmpresa cEmpresa { get; set; }
        public virtual mEmpleado mEmpleado { get; set; }
    }
}
