//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dEmpleadoDomicilio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dEmpleadoDomicilio()
        {
            this.mEmpleado = new HashSet<mEmpleado>();
        }
    
        public int iddEmpleadoDomicilio { get; set; }
        public int idcMunicipio { get; set; }
        public string colonia { get; set; }
        public string calle { get; set; }
        public string noExterior { get; set; }
        public string noInterior { get; set; }
        public string referencia { get; set; }
        public string codigoPostal { get; set; }
        public string estatus { get; set; }
    
        public virtual cMunicipio cMunicipio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mEmpleado> mEmpleado { get; set; }
    }
}
