//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dPedido
    {
        public int iddPedido { get; set; }
        public int idmPedido { get; set; }
        public int idcMenu { get; set; }
        public int cantidad { get; set; }
        public decimal precioUnitario { get; set; }
        public string notasEspeciales { get; set; }
    
        public virtual cMenu cMenu { get; set; }
        public virtual mPedido mPedido { get; set; }
    }
}
