//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eEmpleadoBaja
    {
        public int ideEmpleadoBaja { get; set; }
        public Nullable<int> idmEmpleado { get; set; }
        public Nullable<int> idmPlaza { get; set; }
        public string empresa { get; set; }
        public string sucursal { get; set; }
        public string rol { get; set; }
        public string idmPlazaJefeInmediato { get; set; }
        public string puesto { get; set; }
        public string area { get; set; }
        public string motivoBaja { get; set; }
        public string tipoBaja { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
        public string observacionesBaja { get; set; }
        public Nullable<bool> recontratable { get; set; }
        public string json { get; set; }
    
        public virtual mPlaza mPlaza { get; set; }
        public virtual mEmpleado mEmpleado { get; set; }
    }
}
