//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eEmpleadoPromocion
    {
        public int ideEmpleadoPromocion { get; set; }
        public int idmEmpleado { get; set; }
        public Nullable<int> idcMotivoMovimiento { get; set; }
        public Nullable<System.DateTime> fechaMovimiento { get; set; }
        public string sueldoActual { get; set; }
        public string sueldoNuevo { get; set; }
        public string puestoActual { get; set; }
        public string puestoNuevo { get; set; }
        public string areaActual { get; set; }
        public string areaNuevo { get; set; }
        public string sucursalActual { get; set; }
        public string sucursalNuevo { get; set; }
        public string jefeInmediatoActual { get; set; }
        public string jefeInmediatoNuevo { get; set; }
        public string observaciones { get; set; }
    
        public virtual cMotivoMovimiento cMotivoMovimiento { get; set; }
        public virtual mEmpleado mEmpleado { get; set; }
    }
}
