//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eEmpleadoContrato
    {
        public int ideEmpleadoContrato { get; set; }
        public int idmEmpleado { get; set; }
        public string noContrato { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fechaInicial { get; set; }
        public Nullable<System.DateTime> fechaFinal { get; set; }
        public Nullable<int> idcTipoContrato { get; set; }
        public Nullable<short> tiempoContrato { get; set; }
        public string proyecto { get; set; }
        public string ruta { get; set; }
    
        public virtual cTipoContrato cTipoContrato { get; set; }
        public virtual mEmpleado mEmpleado { get; set; }
    }
}
