//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eEmpleadoDocumentacion
    {
        public int ideEmpleadoDocumentacion { get; set; }
        public int idmEmpleado { get; set; }
        public Nullable<int> idcDocumento { get; set; }
        public string ruta { get; set; }
    
        public virtual cDocumento cDocumento { get; set; }
        public virtual mEmpleado mEmpleado { get; set; }
    }
}
