//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ePlazaBeneficio
    {
        public int idePlazaBeneficio { get; set; }
        public int idmPlaza { get; set; }
        public int idcBeneficio { get; set; }
        public string tipo { get; set; }
        public string valor { get; set; }
    
        public virtual cBeneficio cBeneficio { get; set; }
        public virtual mPlaza mPlaza { get; set; }
    }
}
