//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterRest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasterRestEntities : DbContext
    {
        public MasterRestEntities()
            : base("name=MasterRestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cArea> cArea { get; set; }
        public virtual DbSet<cBeneficio> cBeneficio { get; set; }
        public virtual DbSet<cCategoria> cCategoria { get; set; }
        public virtual DbSet<cCliente> cCliente { get; set; }
        public virtual DbSet<cDocumento> cDocumento { get; set; }
        public virtual DbSet<cDocumentoProbatorio> cDocumentoProbatorio { get; set; }
        public virtual DbSet<cEmpresa> cEmpresa { get; set; }
        public virtual DbSet<cEntidadFederativa> cEntidadFederativa { get; set; }
        public virtual DbSet<cEscolaridad> cEscolaridad { get; set; }
        public virtual DbSet<cEstadoCivil> cEstadoCivil { get; set; }
        public virtual DbSet<cIncapacidad> cIncapacidad { get; set; }
        public virtual DbSet<cInventario> cInventario { get; set; }
        public virtual DbSet<cMenu> cMenu { get; set; }
        public virtual DbSet<cMesa> cMesa { get; set; }
        public virtual DbSet<cMotivoBaja> cMotivoBaja { get; set; }
        public virtual DbSet<cMotivoMovimiento> cMotivoMovimiento { get; set; }
        public virtual DbSet<cMotivoRequisicion> cMotivoRequisicion { get; set; }
        public virtual DbSet<cMunicipio> cMunicipio { get; set; }
        public virtual DbSet<cProfesion> cProfesion { get; set; }
        public virtual DbSet<cPuesto> cPuesto { get; set; }
        public virtual DbSet<cRol> cRol { get; set; }
        public virtual DbSet<cSucursal> cSucursal { get; set; }
        public virtual DbSet<cTipoBaja> cTipoBaja { get; set; }
        public virtual DbSet<cTipoContrato> cTipoContrato { get; set; }
        public virtual DbSet<cTipoNomina> cTipoNomina { get; set; }
        public virtual DbSet<cUsuario> cUsuario { get; set; }
        public virtual DbSet<dEmpleadoDomicilio> dEmpleadoDomicilio { get; set; }
        public virtual DbSet<dPedido> dPedido { get; set; }
        public virtual DbSet<eEmpleadoBaja> eEmpleadoBaja { get; set; }
        public virtual DbSet<eEmpleadoContrato> eEmpleadoContrato { get; set; }
        public virtual DbSet<eEmpleadoDocumentacion> eEmpleadoDocumentacion { get; set; }
        public virtual DbSet<ePlazaBeneficio> ePlazaBeneficio { get; set; }
        public virtual DbSet<mFactura> mFactura { get; set; }
        public virtual DbSet<mPedido> mPedido { get; set; }
        public virtual DbSet<mPlaza> mPlaza { get; set; }
        public virtual DbSet<eEmpleadoPromocion> eEmpleadoPromocion { get; set; }
        public virtual DbSet<cBanco> cBanco { get; set; }
        public virtual DbSet<mEmpleado> mEmpleado { get; set; }
    }
}
