//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mEmpleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mEmpleado()
        {
            this.cUsuario = new HashSet<cUsuario>();
            this.eEmpleadoContrato = new HashSet<eEmpleadoContrato>();
            this.eEmpleadoDocumentacion = new HashSet<eEmpleadoDocumentacion>();
            this.eEmpleadoPromocion = new HashSet<eEmpleadoPromocion>();
            this.mPedido = new HashSet<mPedido>();
            this.mPlaza = new HashSet<mPlaza>();
            this.eEmpleadoBaja = new HashSet<eEmpleadoBaja>();
        }
    
        public int idmEmpleado { get; set; }
        public int idcEmpresa { get; set; }
        public int iddEmpleadoDomicilio { get; set; }
        public string nombre { get; set; }
        public string paterno { get; set; }
        public string materno { get; set; }
        public Nullable<System.DateTime> fechaContratacion { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string lugarNacimiento { get; set; }
        public string curp { get; set; }
        public string rfc { get; set; }
        public string nss { get; set; }
        public Nullable<System.DateTime> fechaIngresoImss { get; set; }
        public Nullable<int> idcEstadoCivil { get; set; }
        public string nacionalidad { get; set; }
        public string sexo { get; set; }
        public string tipoSangre { get; set; }
        public string correoPersonal { get; set; }
        public string correoCoorporativo { get; set; }
        public string telefonoFijoEmpresa { get; set; }
        public string telefonoExtension { get; set; }
        public string telefonoCelularEmpresa { get; set; }
        public string telefono { get; set; }
        public string telefonoContacto { get; set; }
        public string nombreContacto { get; set; }
        public string parentescoContacto { get; set; }
        public Nullable<int> idcEscolaridad { get; set; }
        public string documentoProbatorio { get; set; }
        public Nullable<int> idcProfesion { get; set; }
        public string institucion { get; set; }
        public string tipoInstitucion { get; set; }
        public string estatusInstitucion { get; set; }
        public string esquemaPago { get; set; }
        public string tipoNomina { get; set; }
        public string noCreditoInfonavit { get; set; }
        public string descuentoInfonavit { get; set; }
        public string factorInfonavit { get; set; }
        public string noCreditoFonacot { get; set; }
        public string descuentoFonacot { get; set; }
        public string factorFonacot { get; set; }
        public Nullable<int> idcBanco { get; set; }
        public string codiSucursal { get; set; }
        public string noCuenta { get; set; }
        public string clabeInterbancaria { get; set; }
        public string salarioMensual { get; set; }
        public string salarioDiario { get; set; }
        public string salarioIntegrado { get; set; }
        public string salarioDiarioExcedente { get; set; }
        public string salarioDiarioCotizacion { get; set; }
        public string fotoPerfil { get; set; }
        public string observaciones { get; set; }
        public string estatus { get; set; }
    
        public virtual cBanco cBanco { get; set; }
        public virtual cEmpresa cEmpresa { get; set; }
        public virtual cEscolaridad cEscolaridad { get; set; }
        public virtual cEstadoCivil cEstadoCivil { get; set; }
        public virtual cProfesion cProfesion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cUsuario> cUsuario { get; set; }
        public virtual dEmpleadoDomicilio dEmpleadoDomicilio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eEmpleadoContrato> eEmpleadoContrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eEmpleadoDocumentacion> eEmpleadoDocumentacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eEmpleadoPromocion> eEmpleadoPromocion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mPedido> mPedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mPlaza> mPlaza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eEmpleadoBaja> eEmpleadoBaja { get; set; }
    }
}
