//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mFactura
    {
        public int idmFactura { get; set; }
        public int idmPedido { get; set; }
        public Nullable<System.DateTime> fechaPago { get; set; }
        public decimal subtotal { get; set; }
        public decimal impuestos { get; set; }
        public decimal total { get; set; }
        public string metodoPago { get; set; }
    
        public virtual mPedido mPedido { get; set; }
    }
}
