//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mPedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mPedido()
        {
            this.dPedido = new HashSet<dPedido>();
            this.mFactura = new HashSet<mFactura>();
        }
    
        public int idmPedido { get; set; }
        public int idcMesa { get; set; }
        public int idmEmpleado { get; set; }
        public Nullable<int> idcCliente { get; set; }
        public Nullable<System.DateTime> fechaPedido { get; set; }
        public string estatus { get; set; }
    
        public virtual cCliente cCliente { get; set; }
        public virtual cMesa cMesa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dPedido> dPedido { get; set; }
        public virtual mEmpleado mEmpleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mFactura> mFactura { get; set; }
    }
}
