//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mPlaza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mPlaza()
        {
            this.eEmpleadoBaja = new HashSet<eEmpleadoBaja>();
            this.ePlazaBeneficio = new HashSet<ePlazaBeneficio>();
            this.mPlaza1 = new HashSet<mPlaza>();
        }
    
        public int idmPlaza { get; set; }
        public int idcEmpresa { get; set; }
        public int idcSucursal { get; set; }
        public Nullable<int> idmEmpleado { get; set; }
        public int idcRol { get; set; }
        public Nullable<int> idmPlazaJefeInmediato { get; set; }
        public int idcPuesto { get; set; }
        public int idcArea { get; set; }
        public string estatus { get; set; }
    
        public virtual cArea cArea { get; set; }
        public virtual cEmpresa cEmpresa { get; set; }
        public virtual cPuesto cPuesto { get; set; }
        public virtual cRol cRol { get; set; }
        public virtual cSucursal cSucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eEmpleadoBaja> eEmpleadoBaja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ePlazaBeneficio> ePlazaBeneficio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mPlaza> mPlaza1 { get; set; }
        public virtual mPlaza mPlaza2 { get; set; }
        public virtual mEmpleado mEmpleado { get; set; }
    }
}
